server:
  port: 8280 

spring:
  application:
    name: service-hello3
    
#feign.hystrix.enabled=true
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/    #注册 中心已经开启认证
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
    